Library/Controllers/KitobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library.Models;
using System.IO;

namespace Library.Controllers
{
    public class KitobController : Controller
    {
        private BazaContext db = new BazaContext();

        // GET: /Kitob/
        public ActionResult Index()
        {
            var kitobs = db.Kitobs.Include(k => k.janr);
            return View(kitobs.ToList());
        }
        public ActionResult Yangilari()
        {
            var kitobs = from a in db.Kitobs.Include(k => k.janr) orderby a.chop_etilg_yil descending select a;
            return View(kitobs.ToList());
        }
       
        public ActionResult GetPoisk()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PostPoisk()
        {
            string avtor = Request.Form["avtor"].ToString(), nomi = Request.Form["nomi"].ToString(), nash = Request.Form["nashriyot"].ToString(),
                janr = Request.Form["janr"].ToString();
            var kitoblar = db.Kitobs.Include(a => a.janr);
            var natija = from a in kitoblar.ToList<Kitob>()
                           where
                               (string.IsNullOrEmpty(avtor) || a.avtor.ToLower().Contains(avtor.ToLower())) &&
                               (string.IsNullOrEmpty(nomi) || a.nomi.ToLower().Contains(nomi.ToLower())) &&
                               (string.IsNullOrEmpty(nash) || a.nashriyot.ToLower().Contains(nash.ToLower())) &&
                               (string.IsNullOrEmpty(janr) || a.janr.janr_nomi.ToLower().Contains(janr.ToLower()))                            
                           select a;
            return View(natija.ToList());
        }
      
        public ActionResult Avtorlar()
        {
            return View(db.Kitobs.ToList());
        }
        public ActionResult Avtor_boyicha(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            string avtor = db.Kitobs.Find(id).avtor;
            if (avtor == null)
            {
                return HttpNotFound();
            }
            var nat = from a in db.Kitobs.Include(b => b.janr) where a.avtor == avtor select a;
            return View(nat.ToList());
        }
        // GET: /Kitob/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kitob kitob = db.Kitobs.Find(id);
            if (kitob == null)
            {
                return HttpNotFound();
            }
            return View(kitob);
        }

        // GET: /Kitob/Create
        public ActionResult Create()
        {
            ViewBag.JanrId = new SelectList(db.Janrs, "JanrId", "janr_nomi");
            return View();
        }

        // POST: /Kitob/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="KitobId,nomi,chop_etilg_yil,avtor,JanrId,nashriyot,betlar_soni,soni,qisqacha_malumot")] Kitob kitob,HttpPostedFileBase f)
        {
            if (f != null && f.ContentLength > 0)
            {
                string path = Path.Combine(Server.MapPath("~/Rasmlar"), Path.GetFileName(f.FileName));
                f.SaveAs(path);
                kitob.rasmi = "/Rasmlar/" + Path.GetFileName(f.FileName);
            }
            if (ModelState.IsValid)
            {
                db.Kitobs.Add(kitob);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.JanrId = new SelectList(db.Janrs, "JanrId", "janr_nomi", kitob.JanrId);
            return View(kitob);
        }

        // GET: /Kitob/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kitob kitob = db.Kitobs.Find(id);
            if (kitob == null)
            {
                return HttpNotFound();
            }
            ViewBag.JanrId = new SelectList(db.Janrs, "JanrId", "janr_nomi", kitob.JanrId);
            return View(kitob);
        }

        // POST: /Kitob/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="KitobId,nomi,chop_etilg_yil,avtor,JanrId,nashriyot,betlar_soni,soni,rasmi,qisqacha_malumot")] Kitob kitob)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kitob).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.JanrId = new SelectList(db.Janrs, "JanrId", "janr_nomi", kitob.JanrId);
            return View(kitob);
        }

        // GET: /Kitob/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kitob kitob = db.Kitobs.Find(id);
            if (kitob == null)
            {
                return HttpNotFound();
            }
            return View(kitob);
        }

        // POST: /Kitob/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kitob kitob = db.Kitobs.Find(id);
            db.Kitobs.Remove(kitob);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Library/Views/Kitob/Avtor_boyicha.cshtml
@model IEnumerable<Library.Models.Kitob>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    @foreach (var item in Model)
    {
        <tr>
            <td width="50" height="70">
                <img src="@item.rasmi" class="im" />
            </td>
            <td>
                @item.nomi<br />@item.chop_etilg_yil.ToShortDateString()<br />@item.avtor
            </td>
        </tr>
        <tr>
            <td colspan="2">
                @Html.ActionLink("Edit", "Edit", new { id = item.KitobId }) |
                @Html.ActionLink("Details", "Details", new { id = item.KitobId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.KitobId })
            </td>
        </tr>
    }
</table>

Library/Views/Kitob/Avtorlar.cshtml
@model IEnumerable<Library.Models.Kitob>
@{
    Layout = null;
}
@foreach (var aa in Model)
{
    <!--<li><a href="#" style="font-size:larger;font-family:'Copperplate Gothic';text-decoration:none">@aa.avtor</a></li>-->
    <p style="font-size:larger;font-family:'Copperplate Gothic'">@Html.ActionLink(aa.avtor, "Avtor_boyicha", new { id = aa.KitobId })</p>
    <p></p>
}

Library/Views/Kitob/Create.cshtml
@model Library.Models.Kitob

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Kitob", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kitob</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.nomi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomi)
                @Html.ValidationMessageFor(model => model.nomi)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.chop_etilg_yil, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.chop_etilg_yil)
                @Html.ValidationMessageFor(model => model.chop_etilg_yil)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.avtor, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.avtor)
                @Html.ValidationMessageFor(model => model.avtor)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JanrId, "JanrId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("JanrId", String.Empty)
                @Html.ValidationMessageFor(model => model.JanrId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nashriyot, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nashriyot)
                @Html.ValidationMessageFor(model => model.nashriyot)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.betlar_soni, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.betlar_soni)
                @Html.ValidationMessageFor(model => model.betlar_soni)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soni, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soni)
                @Html.ValidationMessageFor(model => model.soni)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rasmi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="f" />
                @Html.ValidationMessageFor(model => model.rasmi)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.qisqacha_malumot, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qisqacha_malumot)
                @Html.ValidationMessageFor(model => model.qisqacha_malumot)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Library/Views/Kitob/Delete.cshtml
@model Library.Models.Kitob

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kitob</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.janr.janr_nomi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.janr.janr_nomi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nomi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.chop_etilg_yil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.chop_etilg_yil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avtor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avtor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nashriyot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nashriyot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.betlar_soni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.betlar_soni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rasmi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rasmi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qisqacha_malumot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qisqacha_malumot)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Library/Views/Kitob/Details.cshtml
@model Library.Models.Kitob

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Kitob</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.janr.janr_nomi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.janr.janr_nomi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nomi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.chop_etilg_yil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.chop_etilg_yil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avtor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avtor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nashriyot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nashriyot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.betlar_soni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.betlar_soni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rasmi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rasmi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qisqacha_malumot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qisqacha_malumot)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.KitobId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Library/Views/Kitob/Edit.cshtml
@model Library.Models.Kitob

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kitob</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.KitobId)

        <div class="form-group">
            @Html.LabelFor(model => model.nomi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomi)
                @Html.ValidationMessageFor(model => model.nomi)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.chop_etilg_yil, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.chop_etilg_yil)
                @Html.ValidationMessageFor(model => model.chop_etilg_yil)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.avtor, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.avtor)
                @Html.ValidationMessageFor(model => model.avtor)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JanrId, "JanrId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("JanrId", String.Empty)
                @Html.ValidationMessageFor(model => model.JanrId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nashriyot, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nashriyot)
                @Html.ValidationMessageFor(model => model.nashriyot)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.betlar_soni, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.betlar_soni)
                @Html.ValidationMessageFor(model => model.betlar_soni)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soni, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soni)
                @Html.ValidationMessageFor(model => model.soni)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rasmi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rasmi)
                @Html.ValidationMessageFor(model => model.rasmi)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.qisqacha_malumot, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qisqacha_malumot)
                @Html.ValidationMessageFor(model => model.qisqacha_malumot)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Library/Views/Kitob/GetPoisk.cshtml
@{
    ViewBag.Title = "Poisk";
}

<h2>Poisk</h2>
<form method="post" action="PostPoisk">
    <table style="width:30%" align="center">
        <tr>
            <td>Avtor FIO:</td>
            <td><input type="text" name="avtor" style="text-align:right" /></td>
        </tr>
        <tr style="height:5px"></tr>
        <tr style="height:5px"></tr>
        <tr>
            <td>Kitob nomi:</td>
            <td><input type="text" name="nomi" style="text-align:right" /></td>
        </tr>
        <tr style="height:5px"></tr>
        <tr>
            <td>Nashriyot nomi:</td>
            <td><input type="text" name="nashriyot" style="text-align:right" /></td>
        </tr>
        <tr>
            <td>Janri:</td>
            <td><input type="text" name="janr" style="text-align:right" /></td>
        </tr>
        <tr style="height:5px"></tr>
    </table><br />
    <center><input type="submit" value="OK" /></center>
</form>

Library/Views/Kitob/Index.cshtml
@model IEnumerable<Library.Models.Kitob>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    @foreach (var item in Model)
    {
        <tr>
            <td width="50" height="70">
                <img src="@item.rasmi" class="im" />
            </td>
            <td>
                @item.nomi<br />@item.chop_etilg_yil.ToShortDateString()<br />@item.avtor
            </td>
        </tr>
        <tr>
            <td colspan="2">
                @Html.ActionLink("Edit", "Edit", new { id = item.KitobId }) |
                @Html.ActionLink("Details", "Details", new { id = item.KitobId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.KitobId })
            </td>
        </tr>
    }
</table>

Library/Views/Kitob/PostPoisk.cshtml
@model IEnumerable<Library.Models.Kitob>

@{
    ViewBag.Title = "Natija";
}

<h2>Natija</h2>
<table>
    @foreach (var item in Model)
    {

        <tr>
            <td width="50" height="70">
                <img src="@item.rasmi" style="width:100%;height:100%" />
            </td>
            <td>
                @item.nomi<br />@item.chop_etilg_yil.ToShortDateString()<br />@item.avtor</td>
        </tr>
        <tr>
            <td colspan="2">
                @Html.ActionLink("Edit", "Edit", new { id = item.KitobId }) |
                @Html.ActionLink("Details", "Details", new { id = item.KitobId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.KitobId })
            </td>
        </tr>

    }
</table>

Library/Views/Kitob/Yangilari.cshtml
@model IEnumerable<Library.Models.Kitob>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    @foreach (var item in Model)
    {
        <tr>
            <td width="50" height="70">
                <img src="@item.rasmi" class="im" />
            </td>
            <td>
                @item.nomi<br />@item.chop_etilg_yil.ToShortDateString()<br />@item.avtor
            </td>
        </tr>
        <tr>
            <td colspan="2">
                @Html.ActionLink("Edit", "Edit", new { id = item.KitobId }) |
                @Html.ActionLink("Details", "Details", new { id = item.KitobId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.KitobId })
            </td>
        </tr>
    }
</table>